# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:

# For signing JWT tokens
jwt_secret:

# For accessing Postgres database
postgres:
  user:
  pass:

# For uploading files to S3 like bucket at Digital Ocean
digitalocean:
  access:
  secret:
  endpoint:
  region:
  bucket:

# For translations
deepl_pro_api_key:

# For IP country mapping
ip_geo_api_key:

# For sending emails
postmark_server_token:
sendgrid_api_key:
