default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: interflux_development

test:
  <<: *default
  database: interflux_test

production:
  primary: &primary_production
    <<: *default
    database: interflux_production
    username: <%= Rails.application.credentials.database_username %>
    password: <%= Rails.application.credentials.database_password %>
  # queue:
  #   <<: *primary_production
  #   database: interflux_production_queue
  #   migrations_paths: db/queue_migrate
