upstream api_interflux_com
{
  server unix:/var/www/api.interflux.com/tmp/sockets/puma.sock fail_timeout=0;
}

server
{
  listen 80;
  listen [::]:80;
  server_name api.interflux.com;
  return 301 https://api.interflux.com$request_uri;
}

server
{
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;

  server_name api.interflux.com;
  root /var/www/api.interflux.com/public;

  location /
  {
    try_files $uri @app;
  }

  location @app
  {
    proxy_pass http://api_interflux_com;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header Host $http_host;
  }

  ssl_certificate /etc/letsencrypt/live/api.interflux.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.interflux.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  access_log /var/log/api.interflux.com/nginx-access.log;
  error_log /var/log/api.interflux.com/nginx-error.log;
}
